include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_returning_null_for_void
    - prefer_const_constructors
    - prefer_final_fields
    - sort_constructors_first
    - use_key_in_widget_constructors
